baseURL = 'https://ggr.com/'
languageCode = 'en-us'
title = 'game, game. repeat.'
theme = "lowtech"
uglyurls = true
[permalinks]
  posts = '/:title'
  pages = '/:title'
[author]
name = "Scott Bonds"  # Replace with your name
email = "scott@ggr.com" # Replace with your email address
